# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error(object):
    def setupUi(self, Error):
        Error.setObjectName("Error")
        Error.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(Error)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.stackedWidget.setObjectName("stackedWidget")
        self.no_sol = QtWidgets.QWidget()
        self.no_sol.setObjectName("no_sol")
        self.noti1 = QtWidgets.QLabel(self.no_sol)
        self.noti1.setGeometry(QtCore.QRect(50, 50, 311, 121))
        self.noti1.setObjectName("noti1")
        self.ok_btn = QtWidgets.QPushButton(self.no_sol)
        self.ok_btn.setGeometry(QtCore.QRect(150, 230, 93, 28))
        self.ok_btn.setObjectName("ok_btn")
        self.reset_btn = QtWidgets.QPushButton(self.no_sol)
        self.reset_btn.setGeometry(QtCore.QRect(270, 230, 93, 28))
        self.reset_btn.setObjectName("reset_btn")
        self.stackedWidget.addWidget(self.no_sol)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Error)
        QtCore.QMetaObject.connectSlotsByName(Error)

    def retranslateUi(self, Error):
        _translate = QtCore.QCoreApplication.translate
        Error.setWindowTitle(_translate("Error", "Dialog"))
        self.noti1.setText(_translate("Error", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">This problem has no solution. </span></p><p align=\"center\"><span style=\" font-size:8pt;\">Please try again by checking the input or resetting the board</span></p></body></html>"))
        self.ok_btn.setText(_translate("Error", "OK"))
        self.reset_btn.setText(_translate("Error", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Error = QtWidgets.QDialog()
    ui = Ui_Error()
    ui.setupUi(Error)
    Error.show()
    sys.exit(app.exec_())
